platform: linux
image_resource:
  type: docker-image
inputs:
  - name: cluster_env_files
  - name: pxf_src
  - name: pxf_tarball
  - name: singlecluster
    optional: true
params:
  SECRET_ACCESS_KEY:
  ACCESS_KEY_ID:
  IMPERSONATION: true
  TARGET_OS: centos
run:
  path: pxf_src/concourse/scripts/install_hadoop.bash
