on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # match on any tag

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 5.12.0 (05/05/2020)

            ### Enhancements:

            - [#336](https://github.com/greenplum-db/pxf/pull/336) Add User Option to allow invalid input paths
            - [#333](https://github.com/greenplum-db/pxf/pull/333) Hive: Support column projection on Hive Profiles

            ### Bug Fixes:

            - [#324](https://github.com/greenplum-db/pxf/pull/324) Parquet: Right trim char types during insert

            ### Dependency updates:

            - [#348](https://github.com/greenplum-db/pxf/pull/348) CVE-2020-10672: Upgrade jackson-databind to version 2.9.10.4
            - [#343](https://github.com/greenplum-db/pxf/pull/343) Upgrade hive 2.3.7 and support Java 11 for Hive Profiles
            - [#332](https://github.com/greenplum-db/pxf/pull/332) Hive: Add missing transitive dependency when reading parquet files
            - [#331](https://github.com/greenplum-db/pxf/pull/331) pxf-cli: Update gp-common-go-libs to latest
            - [#315](https://github.com/greenplum-db/pxf/pull/315) Bump greenplum-db/gp-common-go-libs to latest
          draft: true
          prerelease: false
